[[project]]
path = ""
version = "0.9.0"
assembler = "nasm"
instruction_set = "x86-64"

[project.opts]
compiler = "nasm"
compile_flags_txt = ["-Wall", "-I", "src/", "-f", "elf"]
diagnostics = true
default_diagnostics = false
