[build]
target = "i686-none-eabi.json"
rustflags = ["-C", "relocation-model=static", "--emit", "asm"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
